name: Publish Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test

      - name: Persist dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist
      - name: Persist tmp
        uses: actions/upload-artifact@v2
        with:
          name: tmp
          path: ${{ github.workspace }}/tmp

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      - name: Build Sources
        run: npm run build

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Publish Prerelease
        if: "github.event.release.prerelease"
        run: npm publish  --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Release
        if: "!github.event.release.prerelease"
        run: npm pub --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      - name: Build Sources
        run: npm run build

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Publish Prerelease
        if: "github.event.release.prerelease"
        run: npm publish  --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}

      - name: Publish Release
        if: "!github.event.release.prerelease"
        run: npm pub --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}
