name: "Ensure Semantic PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr:
    name: Semantic PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
