name: "Label Dependabot PR"

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  labels:
    runs-on: ubuntu-latest

    # run only for dependabot prs
    if: startsWith(github.event.pull_request.user.login, 'dependabot')

    steps:
      - uses: jurijzahn8019/action-dependabot-bump-range@v0.0.29
        id: checker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Pull Request Label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.checker.outputs.diff != 'major'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "pull: automerge"

      - name: Add Pull Request Label for Version Diff
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "dependency: ${{ steps.checker.outputs.diff }}"
