name: Release from Tag

on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+"

jobs:
  release:
    name: "Create Github Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Tag
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
        run: |
          # if [[ ${{ github. }} ]]
          echo $CONTEXT_GITHUB
          echo "::set-env name=IS_RELEASE:true"

      - name: dummy
        run: |
          printenv
      # - name: Prerelease
      #   uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.TOKEN_GITHUB }}
      #     allow_override: true
      #     prerelease: true
      # - name: Release
      #   uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.TOKEN_GITHUB }}
      #     allow_override: true
